name: iv_interlinear_kjv
description: Comparison of the Inspired Version, a Greek interlinear, and the King James Version.
# Also update version in app code for homepage because the package_info_plus plugin isn't working on iOS
version: 3.0.0+13

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  path: ^1.9.1
  gpt_markdown: ^1.0.19
  markdown_widget: ^2.3.2+8
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro.md
    - assets/databases/text.db
    - assets/databases/ot.db
  fonts:
    # Hebrew and Aramaic
    - family: Ezra
      fonts:
        - asset: assets/fonts/ezra/SILEOTSR.ttf
    # Greek
    - family: Galatia
      fonts:
        - asset: assets/fonts/galatia/GalSILR.ttf