name: database_creator
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  html: ^0.15.6
  sqlite3: ^2.7.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
